package gameComponents;

public enum GamePanels {
    LANDING_PAGE,
    HORSE_CUSTOMIZATION_PAGE,
    TRACK_CONFIGURATION_PAGE,
    RACE_DETAILS_PAGE,
    BETTING_PAGE,
    RACE_STATISTIC_PAGE,
    GAME_PLAYING_PAGE,
    HORSE_DETAILS_PAGE,
    BETTING_STAT_PAGE

}
